# Generated by Django 5.0.7 on 2024-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('users', '0002_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_books',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='library.book'),
        ),
    ]
